/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var g,n=this||self;function aa(a){var b=typeof a;b="object"!=b?b:a?Array.isArray(a)?"array":b:"null";return"array"==b||"object"==b&&"number"==typeof a.length}function p(a){var b=typeof a;return"object"==b&&null!=a||"function"==b}function ba(a,b,c){return a.call.apply(a.bind,arguments)}
function ca(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var e=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(e,d);return a.apply(b,e)}}return function(){return a.apply(b,arguments)}}function q(a,b,c){q=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ba:ca;return q.apply(null,arguments)}
function r(a,b){function c(){}c.prototype=b.prototype;a.B=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.Sa=function(d,e,f){for(var h=Array(arguments.length-2),k=2;k<arguments.length;k++)h[k-2]=arguments[k];return b.prototype[e].apply(d,h)}};var t;var da=Array.prototype.indexOf?function(a,b,c){return Array.prototype.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if("string"===typeof a)return"string"!==typeof b||1!=b.length?-1:a.indexOf(b,c);for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},ea=Array.prototype.forEach?function(a,b,c){Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e="string"===typeof a?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)};
function fa(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};function u(){var a=n.navigator;return a&&(a=a.userAgent)?a:""};function v(a){v[" "](a);return a}v[" "]=function(){};var ha=-1!=u().indexOf("Gecko")&&!(-1!=u().toLowerCase().indexOf("webkit")&&-1==u().indexOf("Edge"))&&!(-1!=u().indexOf("Trident")||-1!=u().indexOf("MSIE"))&&-1==u().indexOf("Edge"),w=-1!=u().toLowerCase().indexOf("webkit")&&-1==u().indexOf("Edge");function x(a,b,c){for(var d in a)b.call(c,a[d],d,a)}function ia(a,b,c){for(var d in a)if(b.call(c,a[d],d,a))return!0;return!1}var y="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");function ja(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<y.length;f++)c=y[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};function z(a,b){this.ea=b===A?a:""}z.prototype.toString=function(){return this.ea.toString()};z.prototype.na=!0;z.prototype.ka=function(){return this.ea.toString()};var ka=/^(?:(?:https?|mailto|ftp):|[^:/?#]*(?:[/?#]|$))/i,A={};function la(a,b){x(b,function(c,d){c&&"object"==typeof c&&c.na&&(c=c.ka());"style"==d?a.style.cssText=c:"class"==d?a.className=c:"for"==d?a.htmlFor=c:B.hasOwnProperty(d)?a.setAttribute(B[d],c):0==d.lastIndexOf("aria-",0)||0==d.lastIndexOf("data-",0)?a.setAttribute(d,c):a[d]=c})}
var B={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",nonce:"nonce",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};
function C(a,b,c,d){function e(k){k&&b.appendChild("string"===typeof k?a.createTextNode(k):k)}for(;d<c.length;d++){var f=c[d];if(!aa(f)||p(f)&&0<f.nodeType)e(f);else{a:{if(f&&"number"==typeof f.length){if(p(f)){var h="function"==typeof f.item||"string"==typeof f.item;break a}if("function"===typeof f){h="function"==typeof f.item;break a}}h=!1}ea(h?fa(f):f,e)}}}function ma(a,b){b=String(b);"application/xhtml+xml"===a.contentType&&(b=b.toLowerCase());return a.createElement(b)}
function D(a){for(var b;b=a.firstChild;)a.removeChild(b)}function E(a){return 9==a.nodeType?a:a.ownerDocument||a.document}function na(a){return a.contentDocument||a.contentWindow.document}function F(a){this.o=a||n.document||document}g=F.prototype;g.getElementsByTagName=function(a,b){return(b||this.o).getElementsByTagName(String(a))};
g.g=function(a,b,c){var d=this.o,e=arguments,f=e[1],h=ma(d,String(e[0]));f&&("string"===typeof f?h.className=f:Array.isArray(f)?h.className=f.join(" "):la(h,f));2<e.length&&C(d,h,e,2);return h};g.createElement=function(a){return ma(this.o,a)};g.createTextNode=function(a){return this.o.createTextNode(String(a))};g.la=function(){var a=this.o;return a.parentWindow||a.defaultView};g.appendChild=function(a,b){a.appendChild(b)};g.append=function(a,b){C(E(a),a,arguments,1)};
g.canHaveChildren=function(a){if(1!=a.nodeType)return!1;switch(a.tagName){case "APPLET":case "AREA":case "BASE":case "BR":case "COL":case "COMMAND":case "EMBED":case "FRAME":case "HR":case "IMG":case "INPUT":case "IFRAME":case "ISINDEX":case "KEYGEN":case "LINK":case "NOFRAMES":case "NOSCRIPT":case "META":case "OBJECT":case "PARAM":case "SCRIPT":case "SOURCE":case "STYLE":case "TRACK":case "WBR":return!1}return!0};g.removeNode=function(a){return a&&a.parentNode?a.parentNode.removeChild(a):null};
g.contains=function(a,b){if(!a||!b)return!1;if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a};function G(){this.N=this.N;this.Y=this.Y}G.prototype.N=!1;G.prototype.Ca=function(){this.N||(this.N=!0,this.m())};G.prototype.m=function(){if(this.Y)for(;this.Y.length;)this.Y.shift()()};function H(a,b){this.type=a;this.currentTarget=this.target=b;this.defaultPrevented=this.I=!1}H.prototype.stopPropagation=function(){this.I=!0};H.prototype.preventDefault=function(){this.defaultPrevented=!0};var oa=function(){if(!n.addEventListener||!Object.defineProperty)return!1;var a=!1,b=Object.defineProperty({},"passive",{get:function(){a=!0}});try{n.addEventListener("test",function(){},b),n.removeEventListener("test",function(){},b)}catch(c){}return a}();function I(a,b){H.call(this,a?a.type:"");this.relatedTarget=this.currentTarget=this.target=null;this.button=this.screenY=this.screenX=this.clientY=this.clientX=this.offsetY=this.offsetX=0;this.key="";this.charCode=this.keyCode=0;this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.state=null;this.pointerId=0;this.pointerType="";this.s=null;a&&this.Ha(a,b)}r(I,H);var pa={2:"touch",3:"pen",4:"mouse"};
I.prototype.Ha=function(a,b){var c=this.type=a.type,d=a.changedTouches&&a.changedTouches.length?a.changedTouches[0]:null;this.target=a.target||a.srcElement;this.currentTarget=b;if(b=a.relatedTarget){if(ha){a:{try{v(b.nodeName);var e=!0;break a}catch(f){}e=!1}e||(b=null)}}else"mouseover"==c?b=a.fromElement:"mouseout"==c&&(b=a.toElement);this.relatedTarget=b;d?(this.clientX=void 0!==d.clientX?d.clientX:d.pageX,this.clientY=void 0!==d.clientY?d.clientY:d.pageY,this.screenX=d.screenX||0,this.screenY=
d.screenY||0):(this.offsetX=w||void 0!==a.offsetX?a.offsetX:a.layerX,this.offsetY=w||void 0!==a.offsetY?a.offsetY:a.layerY,this.clientX=void 0!==a.clientX?a.clientX:a.pageX,this.clientY=void 0!==a.clientY?a.clientY:a.pageY,this.screenX=a.screenX||0,this.screenY=a.screenY||0);this.button=a.button;this.keyCode=a.keyCode||0;this.key=a.key||"";this.charCode=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.pointerId=
a.pointerId||0;this.pointerType="string"===typeof a.pointerType?a.pointerType:pa[a.pointerType]||"";this.state=a.state;this.s=a;a.defaultPrevented&&I.B.preventDefault.call(this)};I.prototype.stopPropagation=function(){I.B.stopPropagation.call(this);this.s.stopPropagation?this.s.stopPropagation():this.s.cancelBubble=!0};I.prototype.preventDefault=function(){I.B.preventDefault.call(this);var a=this.s;a.preventDefault?a.preventDefault():a.returnValue=!1};var qa="closure_listenable_"+(1E6*Math.random()|0);function J(a){return!(!a||!a[qa])};var ra=0;function sa(a,b,c,d,e,f){this.listener=a;this.proxy=b;this.src=c;this.type=d;this.capture=!!e;this.S=f;this.key=++ra;this.J=this.M=!1}sa.prototype.X=function(){this.J=!0;this.S=this.src=this.proxy=this.listener=null};function K(a){this.src=a;this.h={};this.K=0}g=K.prototype;g.add=function(a,b,c,d,e){var f=a.toString();a=this.h[f];a||(a=this.h[f]=[],this.K++);var h=L(a,b,d,e);-1<h?(b=a[h],c||(b.M=!1)):(b=new sa(b,null,this.src,f,!!d,e),b.M=c,a.push(b));return b};g.remove=function(a,b,c,d){a=a.toString();if(!(a in this.h))return!1;var e=this.h[a];b=L(e,b,c,d);return-1<b?(e[b].X(),Array.prototype.splice.call(e,b,1),0==e.length&&(delete this.h[a],this.K--),!0):!1};
g.wa=function(a){var b=a.type;if(!(b in this.h))return!1;var c=this.h[b],d=da(c,a),e;(e=0<=d)&&Array.prototype.splice.call(c,d,1);e&&(a.X(),0==this.h[b].length&&(delete this.h[b],this.K--));return e};g.fa=function(a){a=a&&a.toString();var b=0,c;for(c in this.h)if(!a||c==a){for(var d=this.h[c],e=0;e<d.length;e++)++b,d[e].X();delete this.h[c];this.K--}return b};g.H=function(a,b,c,d){a=this.h[a.toString()];var e=-1;a&&(e=L(a,b,c,d));return-1<e?a[e]:null};
g.hasListener=function(a,b){var c=void 0!==a,d=c?a.toString():"",e=void 0!==b;return ia(this.h,function(f){for(var h=0;h<f.length;++h)if(!(c&&f[h].type!=d||e&&f[h].capture!=b))return!0;return!1})};function L(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.J&&f.listener==b&&f.capture==!!c&&f.S==d)return e}return-1};var M="closure_lm_"+(1E6*Math.random()|0),N={},ta=0;function O(a,b,c,d,e){if(d&&d.once)return P(a,b,c,d,e);if(Array.isArray(b)){for(var f=0;f<b.length;f++)O(a,b[f],c,d,e);return null}c=Q(c);return J(a)?a.j(b,c,p(d)?!!d.capture:!!d,e):ua(a,b,c,!1,d,e)}
function ua(a,b,c,d,e,f){if(!b)throw Error("Invalid event type");var h=p(e)?!!e.capture:!!e,k=R(a);k||(a[M]=k=new K(a));c=k.add(b,c,d,h,f);if(c.proxy)return c;d=va();c.proxy=d;d.src=a;d.listener=c;if(a.addEventListener)oa||(e=h),void 0===e&&(e=!1),a.addEventListener(b.toString(),d,e);else if(a.attachEvent)a.attachEvent(wa(b.toString()),d);else if(a.addListener&&a.removeListener)a.addListener(d);else throw Error("addEventListener and attachEvent are unavailable.");ta++;return c}
function va(){function a(c){return b.call(a.src,a.listener,c)}var b=xa;return a}function P(a,b,c,d,e){if(Array.isArray(b)){for(var f=0;f<b.length;f++)P(a,b[f],c,d,e);return null}c=Q(c);return J(a)?a.qa(b,c,p(d)?!!d.capture:!!d,e):ua(a,b,c,!0,d,e)}function ya(a,b,c,d,e){if(Array.isArray(b)){for(var f=0;f<b.length;f++)ya(a,b[f],c,d,e);return null}d=p(d)?!!d.capture:!!d;c=Q(c);if(J(a))return a.ha(b,c,d,e);if(!a)return!1;if(a=R(a))if(b=a.H(b,c,d,e))return S(b);return!1}
function S(a){if("number"===typeof a||!a||a.J)return!1;var b=a.src;if(J(b))return b.ya(a);var c=a.type,d=a.proxy;b.removeEventListener?b.removeEventListener(c,d,a.capture):b.detachEvent?b.detachEvent(wa(c),d):b.addListener&&b.removeListener&&b.removeListener(d);ta--;(c=R(b))?(c.wa(a),0==c.K&&(c.src=null,b[M]=null)):a.X();return!0}function wa(a){return a in N?N[a]:N[a]="on"+a}function xa(a,b){if(a.J)a=!0;else{b=new I(b,this);var c=a.listener,d=a.S||a.src;a.M&&S(a);a=c.call(d,b)}return a}
function R(a){a=a[M];return a instanceof K?a:null}var T="__closure_events_fn_"+(1E9*Math.random()>>>0);function Q(a){if("function"===typeof a)return a;a[T]||(a[T]=function(b){return a.handleEvent(b)});return a[T]};function U(a){G.call(this);this.u=a;this.v={}}r(U,G);var za=[];g=U.prototype;g.j=function(a,b,c,d){return this.Ka(a,b,c,d)};g.Ka=function(a,b,c,d,e){Array.isArray(b)||(b&&(za[0]=b.toString()),b=za);for(var f=0;f<b.length;f++){var h=O(a,b[f],c||this.handleEvent,d||!1,e||this.u||this);if(!h)break;this.v[h.key]=h}return this};g.qa=function(a,b,c,d){return this.ra(a,b,c,d)};
g.ra=function(a,b,c,d,e){if(Array.isArray(b))for(var f=0;f<b.length;f++)this.ra(a,b[f],c,d,e);else{a=P(a,b,c||this.handleEvent,d,e||this.u||this);if(!a)return this;this.v[a.key]=a}return this};g.ha=function(a,b,c,d,e){if(Array.isArray(b))for(var f=0;f<b.length;f++)this.ha(a,b[f],c,d,e);else c=c||this.handleEvent,d=p(d)?!!d.capture:!!d,e=e||this.u||this,c=Q(c),d=!!d,b=J(a)?a.H(b,c,d,e):a?(a=R(a))?a.H(b,c,d,e):null:null,b&&(S(b),delete this.v[b.key]);return this};
g.fa=function(){x(this.v,function(a,b){this.v.hasOwnProperty(b)&&S(a)},this);this.v={}};g.m=function(){U.B.m.call(this);this.fa()};g.handleEvent=function(){throw Error("EventHandler.handleEvent not implemented");};function Aa(a,b,c,d,e,f,h){this.u=h;this.ia=this.L=null;this.A=1;this.Ja=c;this.l=a?new F(E(a)):t||(t=new F);this.ja=new U(this);a=this.l;d=a.g("DIV",{className:"switcherOuter",style:"left:"+c+"px;top:"+d+"px;width:"+e+";height:"+f+";"});a.appendChild(b,d);this.ba=d;b=d.offsetWidth-13-2;this.O=a.g("DIV",{className:"switcherContent",style:"left:"+c+"px;top:0;width:"+(b-7-c)+"px;height:80%;"},a.g("TABLE","switcherTable",a.g("TBODY",null,this.aa=a.g("TR"))));d.appendChild(this.O);this.F=a.g("DIV",{className:"switcherArrows",
style:"left:"+b+"px;top:0;width:13px;height:50%;"},a.g("B",null,">"));d.appendChild(this.F);this.D=a.g("DIV",{className:"switcherArrows",style:"left:"+b+"px;top:"+d.offsetHeight/2+"px;width:13px;height:50%;"},a.g("B",null,"<"));d.appendChild(this.D);this.ja.j(this.D,"mouseover",this.Oa).j(this.F,"mouseover",this.Pa).j(this.D,"mouseout",this.Ma).j(this.F,"mouseout",this.Na).j(this.D,"mousedown",this.va).j(this.F,"mousedown",this.va);this.G=0;this.U=null}g=Aa.prototype;
g.clear=function(a){if(a){a=this.aa.cells.length;for(var b=0;b<a;b++)this.aa.deleteCell(0)}else D(this.ba),this.ba=null};g.Ba=function(a){var b=this.aa.cells.length,c=this.aa;c.insertCell(b);var d=c.cells[b];D(d);d.appendChild(this.l.createTextNode(a.name));d.item=a;d=c.cells[b];d.className="switcherItem";a.initialSheet&&this.C(a,d,!1);this.ja.j(d,"click",q(this.C,this,a,d,!0));return d};g.za=function(a,b){null==this.L&&this.C(a,b,!1)};
g.C=function(a,b,c){a!=this.L&&(null!=this.L&&(this.ia.className="switcherItem"),this.L=a,this.ia=b,b.className="switcherItemActive",b=this.u,null!=b&&b(a,c))};g.Ra=function(){var a=this.ba.offsetWidth-13-2;this.O.style.width=a-7-this.Ja+"px";this.F.style.left=a+"px";this.D.style.left=a+"px"};g.xa=function(){this.O.scrollLeft+=1*this.A*this.G};g.Oa=function(){this.A=1;this.G=-1;this.U=window.setInterval(q(this.xa,this),10)};
g.Pa=function(){this.G=this.A=1;this.U=window.setInterval(q(this.xa,this),10)};g.Ma=function(){window.clearInterval(this.U);this.G=0};g.Na=function(){window.clearInterval(this.U);this.G=0};g.va=function(){4>this.A?this.A++:this.A=1};g.cleanup=function(){this.u=null};function V(){G.call(this);this.i=new K(this);this.Aa=this;this.da=null}r(V,G);V.prototype[qa]=!0;g=V.prototype;g.addEventListener=function(a,b,c,d){O(this,a,b,c,d)};g.removeEventListener=function(a,b,c,d){ya(this,a,b,c,d)};
g.dispatchEvent=function(a){var b=this.da;if(b){var c=[];for(var d=1;b;b=b.da)c.push(b),++d}b=this.Aa;d=a.type||a;if("string"===typeof a)a=new H(a,b);else if(a instanceof H)a.target=a.target||b;else{var e=a;a=new H(d,b);ja(a,e)}e=!0;if(c)for(var f=c.length-1;!a.I&&0<=f;f--){var h=a.currentTarget=c[f];e=h.R(d,!0,a)&&e}a.I||(h=a.currentTarget=b,e=h.R(d,!0,a)&&e,a.I||(e=h.R(d,!1,a)&&e));if(c)for(f=0;!a.I&&f<c.length;f++)h=a.currentTarget=c[f],e=h.R(d,!1,a)&&e;return e};
g.m=function(){V.B.m.call(this);this.Qa();this.da=null};g.j=function(a,b,c,d){return this.i.add(String(a),b,!1,c,d)};g.qa=function(a,b,c,d){return this.i.add(String(a),b,!0,c,d)};g.ha=function(a,b,c,d){return this.i.remove(String(a),b,c,d)};g.ya=function(a){return this.i.wa(a)};g.Qa=function(a){return this.i?this.i.fa(a):0};
g.R=function(a,b,c){a=this.i.h[String(a)];if(!a)return!0;a=a.concat();for(var d=!0,e=0;e<a.length;++e){var f=a[e];if(f&&!f.J&&f.capture==b){var h=f.listener,k=f.S||f.src;f.M&&this.ya(f);d=!1!==h.call(k,c)&&d}}return d&&!c.defaultPrevented};g.H=function(a,b,c,d){return this.i.H(String(a),b,c,d)};g.hasListener=function(a,b){return this.i.hasListener(void 0!==a?String(a):void 0,b)};function W(a,b){V.call(this);this.T=a;this.Ga=!!b;this.pa=this.oa();this.pa||(this.Z=O(this.T,"load",this.ma,!1,this),this.ca=window.setInterval(q(this.ma,this),100))}r(W,V);g=W.prototype;g.Z=null;g.ua=function(){this.ca&&(window.clearInterval(this.ca),this.ca=null)};g.m=function(){delete this.T;this.ua();S(this.Z);W.B.m.call(this)};g.oa=function(){var a=!1;try{var b=na(this.T).body;a=this.Ga?!!b&&!!b.firstChild:!!b}catch(c){}return a};
g.ma=function(){this.oa()&&(this.ua(),S(this.Z),this.Z=null,this.pa=!0,this.dispatchEvent("ifload"))};function Ba(a,b,c,d,e,f,h,k){this.l=a?new F(E(a)):t||(t=new F);this.Ia=k;this.W=this.V=null;var l=this.l;f=l.g("TABLE",{style:"position:relative;left:"+c+"px;top:"+d+"px;width:"+e+";height:"+f+";",cellpadding:0,cellspacing:0},c=l.g("TBODY",null,l.g("TR",null,l.g("TD",null,e=l.g("DIV",{style:"left:0px;top:0px;width:100%;height:100%;overflow:auto"}))),l.g("TR",null,d=l.g("TD",{style:"height:26px;background-color:#eee"}))));l.appendChild(b,f);this.P=e;this.ga=a=new Aa(a,d,0,0,"100%","100%",q(this.La,
this));k&&(k=l.g("DIV","element-link","\u00a0"),l.appendChild(c,l.g("TR",null,l.g("TD","element-link-container",k))),O(k,"click",function(){var m="http://www.google.com/webelements/";m instanceof z||(m="object"==typeof m&&m.na?m.ka():String(m),ka.test(m)||(m="about:invalid#zClosurez"),m=new z(m,A));n.open(m instanceof z&&m.constructor===z?m.ea:"type_error:SafeUrl","")}));if(h.length){l=null;for(k=0;k<h.length;k++)b=a.Ba(h[k]),0==k&&(l=b);a.za(h[0],l)}O(this.l.la(),"message",q(this.Fa,this))}g=Ba.prototype;
g.La=function(a,b){a=q(this.C,this,a,b);if("function"!==typeof a)if(a&&"function"==typeof a.handleEvent)a=q(a.handleEvent,a);else throw Error("Invalid listener argument");2147483647<Number(20)||n.setTimeout(a,20)};
g.C=function(a,b){var c=a.pageUrl,d=this.P;D(d);this.W=null;var e=this.l;c=e.g("IFRAME",{id:"pageswitcher-content",style:"display: block; width: 100%; height:100%;",frameBorder:"0",marginHeight:"0",marginWidth:"0",src:c});var f=new W(c,!0);P(f,"ifload",q(this.Da,this));e.appendChild(d,c);b&&void 0!==a.gid&&(window.location.hash="#gid="+a.gid)};g.Da=function(a){a=a.target;this.W=a.T;a.Ca();this.V&&this.sa()};
g.Fa=function(a){a=a.s;var b=a.origin,c=b.length-11;0<=c&&b.indexOf(".google.com",c)==c&&"SendKeyboardEvents"==a.data&&(this.V=a.origin,this.ta(this.l.o),this.sa())};g.sa=function(){this.W&&this.ta(na(this.W))};g.ta=function(a){O(a,["keydown","keyup","keypress"],q(this.Ea,this))};g.Ea=function(a){if(this.V){var b=this.l.la().parent;b&&b.postMessage&&b.postMessage(JSON.stringify({type:a.type,ctrlKey:a.ctrlKey,altKey:a.altKey,shiftKey:a.shiftKey,metaKey:a.metaKey,keyCode:a.keyCode}),this.V)}};
g.resize=function(a,b){var c=this.P.style;c.width=a+"px";c.height=b-26-(this.Ia?24:0)+"px";this.ga.Ra()};g.cleanup=function(){this.ga.cleanup();this.ga=null;D(this.P);this.P=null};function Ca(a,b,c,d,e,f,h,k,l){return new Ba(b,c,d,e,f,h,k,l)}var X=["_getWGTPageSwitcher"],Y=n;X[0]in Y||"undefined"==typeof Y.execScript||Y.execScript("var "+X[0]);for(var Z;X.length&&(Z=X.shift());)X.length||void 0===Ca?Y=Y[Z]&&Y[Z]!==Object.prototype[Z]?Y[Z]:Y[Z]={}:Y[Z]=Ca;
